name: Update blocklist
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Generate new blocklist
      run: |
        python fetch-lists.py
    - name: Commit to GitHub
      uses: EndBug/add-and-commit@v8
      with:
        author_name: actions-user
        author_email: actions@github.com
